module_login = "Login"

#########
# Login #
#########
bind_ip = "Bind IP"
tt_bind_ip = "Makes your session only work with your current IP. Deselect only when you got automatic logouts or no working login"
mt_login_form = "Login"
md_login_form = "Login to this website."
err_login_failed = "Authentication failure. You have %s more attempt(s) until you are banned for %s."
err_login_ban = "Too much authentication failures, you are now blocked. Please wait %s until you try again."
msg_authenticated = "Welcome back %s! You have been authenticated for the very first time!"
msg_authenticated_again = "Welcome back %s! You have been authenticated again. Your last login was %s from %s."
msg_authenticated_backto = "You can now go back to %s."
mails_login_threat = "Failed Login"
mailb_login_threat = "Dear %s\n\nThere has been a failed login attempt on %s from this IP:\n%s.\n\nWe just wanted to let you know!\n\nSincerly,\nThe {1} System."

##########
# Logout #
##########
mt_login_logout = "Logout"
md_login_logout = "Logout of your account."
msg_logged_out = "You are now logged out."

##########
# Change #
##########
mt_login_change_password = "Change Password"
md_login_change_password = "Change Password"
err_wrong_password = "The provided password is wrong."
err_password_retype = "Your new password does not match the retype."
msg_password_changed = "Your password has been changed successfully."
old_password = "Old Password"
new_password = "New Password"
retype = "Retype New Password"
